---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.30.1"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "4babf5df7ea909f42b0390b5c38fb8d3632b810d"
    sha: "4babf5d"
  parameters:
    - "version": "0.1.0"
    - "groupId": "com.test"
    - "description": "Show bugs with JavaType"
    - "owner": "matthew"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.30.1"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "4babf5df7ea909f42b0390b5c38fb8d3632b810d"
    sha: "4babf5d"
  parameters:
    - "editorName": "AddImport"
    - "description": "Add an import to a JavaType"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.30.1"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "4babf5df7ea909f42b0390b5c38fb8d3632b810d"
    sha: "4babf5d"
  parameters:
    - "editorName": "AddAnnotation"
    - "description": "Add an annotation to a JavaType"

